- project:
    check: &jobs
      jobs:
        - cabal-test:
            vars:
              ghc_version: 8.8
              cabal_install_args: "--lib"
              cabal_build_args: "--write-ghc-environment-files=always"
              cabal_target: "all"
            nodeset:
              nodes:
                - name: container
                  label: zuul-worker-haskell
        - hlint:
            nodeset:
              nodes:
                - name: container
                  label: zuul-worker-haskell
    gate: *jobs
